name: Daily IG Post
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Main Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BUFFER_ACCESS_TOKEN: ${{ secrets.BUFFER_ACCESS_TOKEN }}
          BUFFER_PROFILE_ID: ${{ secrets.BUFFER_PROFILE_ID }}
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
        run: python src/main.py
